CREATE TABLE [dbo].[ANALYSIS] (
    [NAME]          VARCHAR (15)  NOT NULL,
    [VERSION]       INT           NOT NULL,
    [ACTIVE]        VARCHAR (1)   NULL,
    [REPORTED_NAME] VARCHAR (20)  NULL,
    [COMMON_NAME]   VARCHAR (20)  NULL,
    [ANALYSIS_TYPE] VARCHAR (10)  NULL,
    [DESCRIPTION]   VARCHAR (254) NULL,
    [CHANGED_ON]    DATETIME      NULL,
    CONSTRAINT [PK_ANALYSIS] PRIMARY KEY NONCLUSTERED ([NAME] ASC, [VERSION] ASC)
);


GO
CREATE UNIQUE CLUSTERED INDEX [PK__ANALYSIS__ECC68B8349DC32AC]
    ON [dbo].[ANALYSIS]([NAME] ASC, [VERSION] ASC);

