CREATE TABLE [dbo].[COMPONENT] (
    [NAME]         VARCHAR (40) NOT NULL,
    [ANALYSIS]     VARCHAR (15) NOT NULL,
    [VERSION]      INT          NOT NULL,
    [ORDER_NUMBER] INT          NULL,
    [RESULT_TYPE]  VARCHAR (1)  NULL,
    [REPORTABLE]   VARCHAR (1)  NULL,
    [OPTIONAL]     VARCHAR (1)  NULL,
    CONSTRAINT [PK_COMPONENT] PRIMARY KEY CLUSTERED ([ANALYSIS] ASC, [NAME] ASC, [VERSION] ASC),
    CONSTRAINT [FK_COMPONENT_ANALYSIS] FOREIGN KEY ([ANALYSIS], [VERSION]) REFERENCES [dbo].[ANALYSIS] ([NAME], [VERSION])
);

