CREATE TABLE [dbo].[MPI Extract 3] (
    [System Code]                          VARCHAR (10) NOT NULL,
    [Specimen ID]                          VARCHAR (10) NOT NULL,
    [Lab Number]                           VARCHAR (20) NOT NULL,
    [Person ID]                            VARCHAR (20) NULL,
    [PHOCIS ID]                            VARCHAR (20) NULL,
    [Update Timestamp]                     VARCHAR (14) NULL,
    [Event Date]                           VARCHAR (8)  NULL,
    [Event Location Type]                  CHAR (1)     NULL,
    [Event Location Address 1 Type]        CHAR (1)     NULL,
    [Event Location Address 1 Line 1]      VARCHAR (80) NULL,
    [Event Location City]                  VARCHAR (30) NULL,
    [Event Location ZIP]                   VARCHAR (10) NULL,
    [Event Location County]                VARCHAR (15) NULL,
    [Event Facility Name at Time of Event] VARCHAR (80) NULL,
    [Event Facility ID]                    VARCHAR (30) NULL,
    [First Name]                           VARCHAR (40) NULL,
    [Middle Name]                          VARCHAR (35) NULL,
    [Last Name]                            VARCHAR (40) NULL,
    [Date of Birth]                        VARCHAR (8)  NULL,
    [Gender]                               VARCHAR (8)  NULL,
    [Race 1]                               VARCHAR (20) NULL,
    [Ethnicity]                            VARCHAR (20) NULL,
    [Address 1 Line 1]                     VARCHAR (80) NULL,
    [Address 1 City]                       VARCHAR (30) NULL,
    [Address 1 State]                      VARCHAR (2)  NULL,
    [Address 1 Postal Code]                VARCHAR (10) NULL,
    [Address 1 County]                     VARCHAR (15) NULL
);

