CREATE TABLE [dbo].[PATIENT] (
    [NAME]             VARCHAR (20)  NOT NULL,
    [REVISION_NO]      INT           NOT NULL,
    [ACTIVE_FLAG]      VARCHAR (1)   NULL,
    [FIRST_NAME]       VARCHAR (80)  NULL,
    [LAST_NAME]        VARCHAR (80)  NULL,
    [MIDDLE_NAME]      VARCHAR (80)  NULL,
    [BIRTH_DATE]       DATETIME      NULL,
    [GENDER]           VARCHAR (20)  NULL,
    [ADDRESS1_LINE_1]  VARCHAR (50)  NULL,
    [ADDRESS1_LINE_2]  VARCHAR (50)  NULL,
    [ADDRESS1_CITY]    VARCHAR (30)  NULL,
    [ADDRESS1_STATE]   VARCHAR (20)  NULL,
    [ADDRESS1_ZIP]     VARCHAR (10)  NULL,
    [ADDRESS1_COUNTRY] VARCHAR (20)  NULL,
    [ADDRESS1_COUNTY]  VARCHAR (20)  NULL,
    [ADDRESS1_TYPE]    VARCHAR (20)  NULL,
    [X_RACE]           VARCHAR (254) NULL,
    [X_ETHNICITY]      VARCHAR (254) NULL,
    [Z_PHOCIS_ID]      VARCHAR (20)  NULL,
    [Z_PHIDDO_ID]      VARCHAR (30)  NULL,
    [CHANGED_ON]       DATETIME      NULL,
    [HOME_PHONE]       VARCHAR (80)  NULL,
    CONSTRAINT [PK_PATIENT] PRIMARY KEY NONCLUSTERED ([NAME] ASC, [REVISION_NO] ASC)
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[PATIENT] TO [OSDH\LITS-EPI-SQL]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PATIENT] TO [AGENCY\MediatorApiStaging]
    AS [dbo];

