CREATE TABLE [dbo].[pmlTemp] (
    [LabWareKey]         INT           NOT NULL,
    [DemographicsID]     INT           NULL,
    [EncounterID]        INT           NULL,
    [LabNumber]          VARCHAR (20)  NULL,
    [StartDate]          SMALLDATETIME NULL,
    [EndDate]            SMALLDATETIME NULL,
    [SubmitterProgramID] VARCHAR (2)   NULL,
    [TotalCharges]       SMALLMONEY    NULL,
    [DiagnosisCode1]     VARCHAR (7)   NULL,
    [PC1]                VARCHAR (6)   NULL,
    [DC1REF1]            VARCHAR (1)   NULL,
    [CH1]                SMALLMONEY    NULL,
    [CH1UNITS]           TINYINT       NULL,
    [PC2]                VARCHAR (6)   NULL,
    [DC2REF1]            VARCHAR (1)   NULL,
    [CH2]                SMALLMONEY    NULL,
    [CH2UNITS]           TINYINT       NULL,
    [PC3]                VARCHAR (6)   NULL,
    [DC3REF1]            VARCHAR (1)   NULL,
    [CH3]                SMALLMONEY    NULL,
    [CH3UNITS]           TINYINT       NULL,
    [PC4]                VARCHAR (6)   NULL,
    [DC4REF1]            VARCHAR (1)   NULL,
    [CH4]                SMALLMONEY    NULL,
    [CH4UNITS]           TINYINT       NULL,
    [PC5]                VARCHAR (6)   NULL,
    [DC5REF1]            VARCHAR (1)   NULL,
    [CH5]                SMALLMONEY    NULL,
    [CH5UNITS]           TINYINT       NULL,
    [PC6]                VARCHAR (6)   NULL,
    [DC6REF1]            VARCHAR (1)   NULL,
    [CH6]                SMALLMONEY    NULL,
    [CH6UNITS]           TINYINT       NULL,
    [PC7]                VARCHAR (6)   NULL,
    [DC7REF1]            VARCHAR (1)   NULL,
    [CH7]                SMALLMONEY    NULL,
    [CH7UNITS]           TINYINT       NULL,
    [PC8]                VARCHAR (6)   NULL,
    [DC8REF1]            VARCHAR (1)   NULL,
    [CH8]                SMALLMONEY    NULL,
    [CH8UNITS]           TINYINT       NULL,
    [PC9]                VARCHAR (6)   NULL,
    [DC9REF1]            VARCHAR (1)   NULL,
    [CH9]                SMALLMONEY    NULL,
    [CH9UNITS]           TINYINT       NULL,
    [PC10]               VARCHAR (6)   NULL,
    [DC10REF1]           VARCHAR (1)   NULL,
    [CH10]               SMALLMONEY    NULL,
    [CH10UNITS]          TINYINT       NULL
);


GO
CREATE NONCLUSTERED INDEX [t1_LabWareKey]
    ON [dbo].[pmlTemp]([LabWareKey] ASC);

