CREATE TABLE [dbo].[PRACTITIONER] (
    [NAME]         VARCHAR (30)  NOT NULL,
    [REMOVED]      VARCHAR (1)   NULL,
    [DESCRIPTION]  VARCHAR (254) NULL,
    [X_PRACT_TYPE] VARCHAR (20)  NULL,
    [CHANGED_ON]   DATETIME      NULL,
    CONSTRAINT [PK_PRACTITIONER] PRIMARY KEY NONCLUSTERED ([NAME] ASC)
);

