CREATE TABLE [dbo].[REPORTS] (
    [REPORT_NUMBER]    INT           NOT NULL,
    [REPORT_TYPE]      VARCHAR (40)  NULL,
    [PURPOSE]          VARCHAR (20)  NULL,
    [OBJECT_CLASS]     VARCHAR (10)  NULL,
    [DATE_CREATED]     DATETIME      NULL,
    [CREATED_BY]       VARCHAR (10)  NULL,
    [PRINT_COUNT]      INT           NULL,
    [DATA_CHANGED]     VARCHAR (1)   NULL,
    [RESULTS_CHANGED]  VARCHAR (1)   NULL,
    [REPORT_FILE_NAME] VARCHAR (254) NULL,
    [SUPERSEDED]       VARCHAR (1)   NULL,
    [ALLOW_EDIT]       VARCHAR (1)   NULL,
    [ALLOW_PRINT]      VARCHAR (1)   NULL,
    [REPORT_STATUS]    VARCHAR (1)   NULL,
    [AUDIT]            VARCHAR (1)   NULL,
    CONSTRAINT [PK_REPORTS] PRIMARY KEY NONCLUSTERED ([REPORT_NUMBER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_REPORTS_PURPOSE]
    ON [dbo].[REPORTS]([PURPOSE] ASC)
    INCLUDE([REPORT_NUMBER]);


GO
GRANT SELECT
    ON OBJECT::[dbo].[REPORTS] TO [OSDH\LITS-EPI-SQL]
    AS [dbo];

