CREATE TABLE [dbo].[REPORT_OBJECTS] (
    [REPORT_NUMBER] INT          NOT NULL,
    [OBJECT_ID]     INT          NOT NULL,
    [OBJECT_NAME]   VARCHAR (25) NULL,
    CONSTRAINT [FK_REPORT_OBJECTS_REPORTS] FOREIGN KEY ([REPORT_NUMBER]) REFERENCES [dbo].[REPORTS] ([REPORT_NUMBER]),
    CONSTRAINT [FK_REPORT_OBJECTS_SAMPLE] FOREIGN KEY ([OBJECT_ID]) REFERENCES [dbo].[SAMPLE] ([SAMPLE_NUMBER])
);


GO
CREATE UNIQUE CLUSTERED INDEX [PK__REPORT_O__AE19211E3FF3A116]
    ON [dbo].[REPORT_OBJECTS]([REPORT_NUMBER] ASC);


GO
GRANT SELECT
    ON OBJECT::[dbo].[REPORT_OBJECTS] TO [OSDH\LITS-EPI-SQL]
    AS [dbo];

