CREATE TABLE [dbo].[SAMPLE_Temp] (
    [SAMPLE_NUMBER]      INT          NOT NULL,
    [TEXT_ID]            VARCHAR (30) NULL,
    [STATUS]             VARCHAR (1)  NULL,
    [LOGIN_DATE]         DATETIME     NULL,
    [SAMPLED_DATE]       DATETIME     NULL,
    [RECD_DATE]          DATETIME     NULL,
    [DATE_STARTED]       DATETIME     NULL,
    [STARTED]            VARCHAR (1)  NULL,
    [DATE_COMPLETED]     DATETIME     NULL,
    [DATE_REVIEWED]      DATETIME     NULL,
    [SAMPLE_TYPE]        VARCHAR (10) NULL,
    [SAMPLE_NAME]        VARCHAR (30) NULL,
    [CUSTOMER]           VARCHAR (30) NULL,
    [TEST_LIST]          VARCHAR (20) NULL,
    [SPEC_TYPE]          VARCHAR (20) NULL,
    [RELEASED]           VARCHAR (1)  NULL,
    [RELEASED_ON]        DATETIME     NULL,
    [APPROVED]           VARCHAR (1)  NULL,
    [REPORT_NUMBER]      INT          NULL,
    [PATIENT]            VARCHAR (20) NULL,
    [PATIENT_REV_NO]     INT          NULL,
    [LAB]                VARCHAR (20) NULL,
    [LABEL_ID]           VARCHAR (20) NULL,
    [X_REPORTED]         VARCHAR (1)  NULL,
    [X_LAST_REPORT_DATE] DATETIME     NULL,
    [X_LAST_REPORT_TYPE] VARCHAR (10) NULL,
    [GROUP_NAME]         VARCHAR (10) NULL,
    [X_PRACTITIONER]     VARCHAR (30) NULL,
    [X_SPECIMEN_SOURCE]  VARCHAR (10) NULL,
    [CHANGED_ON]         DATETIME     NULL,
    [Z_Program]          VARCHAR (20) NULL,
    [Z_OK_OUTBREAK]      VARCHAR (50) NULL
);

