CREATE TABLE [dbo].[TEST] (
    [TEST_NUMBER]         INT           NOT NULL,
    [ANALYSIS]            VARCHAR (15)  NULL,
    [VERSION]             INT           NULL,
    [SAMPLE_NUMBER]       INT           NULL,
    [STATUS]              VARCHAR (1)   NULL,
    [DATE_RECEIVED]       DATETIME      NULL,
    [DATE_STARTED]        DATETIME      NULL,
    [DATE_COMPLETED]      DATETIME      NULL,
    [DATE_REVIEWED]       DATETIME      NULL,
    [TEST_COMMENT]        VARCHAR (254) NULL,
    [LAB]                 VARCHAR (20)  NULL,
    [REPORTED_NAME]       VARCHAR (20)  NULL,
    [VARIATION]           VARCHAR (15)  NULL,
    [RELEASED]            VARCHAR (1)   NULL,
    [X_REPORTED]          VARCHAR (1)   NULL,
    [X_FIRST_REPORT_DATE] DATETIME      NULL,
    [X_LAST_REPORT_DATE]  DATETIME      NULL,
    [CHANGED_ON]          DATETIME      NULL,
    CONSTRAINT [PK_TEST] PRIMARY KEY NONCLUSTERED ([TEST_NUMBER] ASC),
    CONSTRAINT [FK_TEST_ANALYSIS] FOREIGN KEY ([ANALYSIS], [VERSION]) REFERENCES [dbo].[ANALYSIS] ([NAME], [VERSION]),
    CONSTRAINT [FK_TEST_SAMPLE] FOREIGN KEY ([SAMPLE_NUMBER]) REFERENCES [dbo].[SAMPLE] ([SAMPLE_NUMBER])
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[TEST] TO [OSDH\LITS-EPI-SQL]
    AS [dbo];

