
CREATE VIEW [dbo].[MICRO_TestResult]
AS
 SELECT dbo.TEST.SAMPLE_NUMBER,
		dbo.TEST.REPORTED_NAME,
		dbo.TEST.TEST_NUMBER,
		dbo.RESULT.RESULT_NUMBER,
		dbo.RESULT.FORMATTED_ENTRY, 
        dbo.RESULT.NAME,
		dbo.RESULT.DATE_REVIEWED
  FROM  dbo.TEST LEFT OUTER JOIN
        dbo.RESULT ON dbo.TEST.TEST_NUMBER = dbo.RESULT.TEST_NUMBER
		          AND dbo.TEST.LAB = 'MICRO'

