--***************************************************************************
--    Procedure Name : [usp_LabWare_LabDataImport]
--
--    Description    : Load relational data from [LabWare_Dev]
--    Author         : LilyL
--    Date Written   : 02/12/2015
--    Current Version: 
--	Vers. # Date:       Author:		Description:
--	8/14/2015			lilyl		Move db to test upudate names
--	------- ----------  ----------	-------------------------------------------
--	11/13/2015			lilyl		Update Prod
---***************************************************************************

CREATE PROCEDURE  [dbo].[usp_LabWare_LabDataImport]

AS
--fill up dbo.ANALYSIS 

Insert into dbo.ANALYSIS
(	NAME,[VERSION],ACTIVE,REPORTED_NAME,
	COMMON_NAME,ANALYSIS_TYPE,[DESCRIPTION], CHANGED_ON
)
Select NAME,[VERSION],ACTIVE,REPORTED_NAME,
       COMMON_NAME,ANALYSIS_TYPE,[DESCRIPTION], CHANGED_ON
From [LabWare_Prod].[dbo].[ANALYSIS]
Where ACTIVE = 'T' and 
	  (X_REPORTABLE = 'T' or X_PRELIMINARY_OS = 'T') and
	  NAME in (select ANALYSIS From [LabWare_Prod].[dbo].Test)and
	  (NAME not in (select NAME from dbo.ANALYSIS) 
	  )
-- fill up  dbo.COMPONENT. use only [LabWare_Lab_Data] ANALYSIS table to pull dbo.COMPONENT
Insert into dbo.COMPONENT
(
	NAME,ANALYSIS,[VERSION],ORDER_NUMBER,RESULT_TYPE,REPORTABLE,OPTIONAL
)
Select 
	c.NAME,a.NAME as ANALYSIS,a.[VERSION],c.ORDER_NUMBER,c.RESULT_TYPE,c.REPORTABLE,c.OPTIONAL
From [dbo].ANALYSIS  a 
left join [LabWare_Prod].[dbo].COMPONENT  c on a.NAME = c.ANALYSIS and  a.[VERSION] = c.[VERSION] 
Where c.REPORTABLE = 'T' 	  
order by a.NAME,c.NAME, a.[VERSION]

--Fix Sample table first:
--Get unique sample number.
IF OBJECT_ID('tempdb..##tempSample') IS NOT NULL
/*Then it exists*/
   DROP TABLE ##tempSample 
	
Select distinct
   SAMPLE_NUMBER  
INTO  ##tempSample 
From [LabWare_Prod].[dbo].[Test] t
	inner join [dbo].COMPONENT c
	on t.ANALYSIS = c.ANALYSIS and t.[VERSION] = c.[VERSION] 	
Where (SAMPLE_NUMBER is NOT NULL) and t.[STATUS] = 'A'

--select * from ##tempSample 
--Need to make sure Sample_Temp each record is unquie.

Insert into dbo.SAMPLE_Temp
(
	SAMPLE_NUMBER,TEXT_ID,[STATUS],LOGIN_DATE,SAMPLED_DATE,RECD_DATE,
	DATE_STARTED,[STARTED],DATE_COMPLETED,DATE_REVIEWED,SAMPLE_TYPE,
	SAMPLE_NAME,CUSTOMER,TEST_LIST,SPEC_TYPE,RELEASED,RELEASED_ON,
	APPROVED,REPORT_NUMBER,PATIENT,PATIENT_REV_NO,LAB,LABEL_ID,
	X_REPORTED,X_LAST_REPORT_DATE,X_LAST_REPORT_TYPE,GROUP_NAME,
	X_PRACTITIONER,X_SPECIMEN_SOURCE,Z_Program,CHANGED_ON, Z_OK_OUTBREAK
)
Select distinct
	SAMPLE_NUMBER,TEXT_ID,[STATUS],LOGIN_DATE,SAMPLED_DATE,RECD_DATE,
	DATE_STARTED,[STARTED],DATE_COMPLETED,DATE_REVIEWED,SAMPLE_TYPE,
	SAMPLE_NAME,CUSTOMER,TEST_LIST,SPEC_TYPE,RELEASED,RELEASED_ON,
	APPROVED,REPORT_NUMBER,PATIENT,PATIENT_REV_NO,LAB,LABEL_ID,
	X_REPORTED,X_LAST_REPORT_DATE,X_LAST_REPORT_TYPE,GROUP_NAME,
	X_PRACTITIONER,X_SPECIMEN_SOURCE,Z_Program, CHANGED_ON, Z_OK_OUTBREAK
From [LabWare_Prod].dbo.[SAMPLE]
Where SAMPLE_NUMBER in (select SAMPLE_NUMBER from ##tempSample)
order by SAMPLE_NUMBER

--fill up dbo.CUSTOMER 
Insert into dbo.CUSTOMER
(
	NAME,REMOVED,COMPANY_NAME,X_CUSTOMER_TYPE,ADDRESS1,ADDRESS2,
	X_CITY,X_STATE,X_ZIPCODE,X_COUNTY,PHONE_NUM,FAX_NUM,ACTIVE,X_NPI,
	Z_PHOCIS_ID,Z_PHIDDO_ID, CHANGED_ON
)
Select distinct
	NAME,REMOVED,COMPANY_NAME,X_CUSTOMER_TYPE,ADDRESS1,ADDRESS2,
	X_CITY,X_STATE,X_ZIPCODE,X_COUNTY,PHONE_NUM,FAX_NUM,ACTIVE,X_NPI,
	Z_PHOCIS_ID,Z_PHIDDO_ID, a.CHANGED_ON
From [LabWare_Prod].[dbo].[CUSTOMER] a
inner join dbo.SAMPLE_Temp b
			on a.NAME = b.CUSTOMER
Order by Name

--fill up dbo.PATIENT with active patient data

Insert into dbo.PATIENT
(
	NAME,REVISION_NO,ACTIVE_FLAG,FIRST_NAME,LAST_NAME,MIDDLE_NAME,
	BIRTH_DATE,GENDER,ADDRESS1_LINE_1,ADDRESS1_LINE_2,ADDRESS1_CITY,
	ADDRESS1_STATE,ADDRESS1_ZIP,ADDRESS1_COUNTRY,ADDRESS1_COUNTY,
	ADDRESS1_TYPE,X_RACE,X_ETHNICITY,Z_PHOCIS_ID,Z_PHIDDO_ID,CHANGED_ON
)
Select distinct
	NAME,REVISION_NO,ACTIVE_FLAG,FIRST_NAME,LAST_NAME,MIDDLE_NAME,
	BIRTH_DATE,GENDER,ADDRESS1_LINE_1,ADDRESS1_LINE_2,ADDRESS1_CITY,
	ADDRESS1_STATE,ADDRESS1_ZIP,ADDRESS1_COUNTRY,ADDRESS1_COUNTY,
	ADDRESS1_TYPE,X_RACE,X_ETHNICITY,Z_PHOCIS_ID,Z_PHIDDO_ID, a.CHANGED_ON
From [LabWare_Prod].dbo.PATIENT a
inner join dbo.SAMPLE_Temp b
on a.NAME = b.PATIENT and a.REVISION_NO = b.PATIENT_REV_NO


--fill up dbo.PRACTITIONER

Insert into dbo.PRACTITIONER
(
	NAME,REMOVED,[DESCRIPTION],X_PRACT_TYPE,CHANGED_ON
)
Select distinct
	NAME,REMOVED,[DESCRIPTION],X_PRACT_TYPE, a.CHANGED_ON
From [LabWare_Prod].dbo.PRACTITIONER a
inner join dbo.SAMPLE_Temp b
on a.NAME = b.X_PRACTITIONER 
order by NAME


--fill up dbo.SAMPLE

Insert into dbo.[SAMPLE]
(
	SAMPLE_NUMBER,TEXT_ID,[STATUS],LOGIN_DATE,SAMPLED_DATE,RECD_DATE,
	DATE_STARTED,[STARTED],DATE_COMPLETED,DATE_REVIEWED,SAMPLE_TYPE,
	SAMPLE_NAME,CUSTOMER,TEST_LIST,SPEC_TYPE,RELEASED,RELEASED_ON,
	APPROVED,REPORT_NUMBER,PATIENT,PATIENT_REV_NO,LAB,LABEL_ID,
	X_REPORTED,X_LAST_REPORT_DATE,X_LAST_REPORT_TYPE,GROUP_NAME,
	X_PRACTITIONER,X_SPECIMEN_SOURCE, CHANGED_ON, Z_Program, Z_OK_OUTBREAK
)
Select distinct
	SAMPLE_NUMBER,TEXT_ID,[STATUS],LOGIN_DATE,SAMPLED_DATE,RECD_DATE,
	DATE_STARTED,[STARTED],DATE_COMPLETED,DATE_REVIEWED,SAMPLE_TYPE,
	SAMPLE_NAME,CUSTOMER,TEST_LIST,SPEC_TYPE,RELEASED,RELEASED_ON,
	APPROVED,REPORT_NUMBER,PATIENT,PATIENT_REV_NO,LAB,LABEL_ID,
	X_REPORTED,X_LAST_REPORT_DATE,X_LAST_REPORT_TYPE,GROUP_NAME,
	X_PRACTITIONER,X_SPECIMEN_SOURCE,s.CHANGED_ON, s.Z_Program, s.Z_OK_OUTBREAK
From dbo.SAMPLE_Temp s
inner join CUSTOMER c on s.CUSTOMER = c.NAME
inner join PRACTITIONER p on s.X_PRACTITIONER = p.NAME
inner join PATIENT a on s.PATIENT = a.NAME and s.PATIENT_REV_NO = a.REVISION_NO
order by SAMPLE_NUMBER


--fill up dbo.TEST

Insert into [dbo].[TEST]
(
   TEST_NUMBER, ANALYSIS, [VERSION],SAMPLE_NUMBER,
   [STATUS],DATE_RECEIVED,DATE_STARTED,DATE_COMPLETED,
   DATE_REVIEWED, TEST_COMMENT, LAB, REPORTED_NAME,
   VARIATION,RELEASED,X_REPORTED,X_FIRST_REPORT_DATE,X_LAST_REPORT_DATE, CHANGED_ON
)
Select distinct
   TEST_NUMBER, t.ANALYSIS, t.[VERSION], t.SAMPLE_NUMBER,
   t.[STATUS],DATE_RECEIVED,t.DATE_STARTED, t.DATE_COMPLETED,
   t.DATE_REVIEWED, TEST_COMMENT, t.LAB ,t.REPORTED_NAME,
   VARIATION,t.RELEASED,t.X_REPORTED,X_FIRST_REPORT_DATE,t.X_LAST_REPORT_DATE, t.CHANGED_ON
From [LabWare_Prod].[dbo].[Test] t
	inner join [dbo].COMPONENT c
	on t.ANALYSIS = c.ANALYSIS and t.[VERSION] = c.[VERSION] 
	inner join 	[dbo].[SAMPLE] s
	on t.SAMPLE_NUMBER = s.SAMPLE_NUMBER
Where (t.SAMPLE_NUMBER is NOT NULL) and t.[STATUS] = 'A' --and t.[X_REPORTABLE] = 'T'
order by TEST_NUMBER


--and t.REPORTED_NAME = c.ANALYSIS
--since dbo.COMPONENT is loaded based on dbo.ANALYSIS so join COMPONENT is good enough
--this was done when pulling in Analysis data:  (t.X_PRELIMINARY ='T' or t.X_PRELIMINARY_OS = 'T' or t.X_REPORTABLE = 'T') 
  

-- fill up dbo.RESULT
 
Insert into [dbo].[RESULT]
(
  RESULT_NUMBER,TEST_NUMBER,NAME, FORMATTED_ENTRY,
  ENTERED_ON,DATE_REVIEWED,ANALYSIS,SAMPLE_NUMBER,
  LOINC,SNOMED_CODE,X_ORGANISM,X_ORGANISM_REF, CHANGED_ON
)
Select
  RESULT_NUMBER,r.TEST_NUMBER,NAME, FORMATTED_ENTRY,
  ENTERED_ON,r.DATE_REVIEWED,r.ANALYSIS,r.SAMPLE_NUMBER,
  LOINC,SNOMED_CODE,X_ORGANISM,X_ORGANISM_REF, r.CHANGED_ON
From [LabWare_Prod].[dbo].[RESULT] r 
	 inner join [dbo].[Test] t
     on r.TEST_NUMBER = t.TEST_NUMBER
where r.[STATUS] = 'A' and r.REPORTABLE = 'T'
  

--fill up #TempReportObj

select distinct
	r.REPORT_NUMBER,[OBJECT_ID],[OBJECT_NAME]
into #TempReportObj
From [LabWare_Prod].dbo.REPORT_OBJECTS r
inner join [dbo].[SAMPLE] s
	on r.[OBJECT_ID] = s.SAMPLE_NUMBER
	

--fill up dbo.REPORTS
Insert into dbo.REPORTS
(
	REPORT_NUMBER,REPORT_TYPE,PURPOSE,OBJECT_CLASS,DATE_CREATED,CREATED_BY,
	PRINT_COUNT,DATA_CHANGED,RESULTS_CHANGED,REPORT_FILE_NAME,SUPERSEDED,
	ALLOW_EDIT,ALLOW_PRINT,REPORT_STATUS,AUDIT
)
Select distinct
	r.REPORT_NUMBER,REPORT_TYPE,PURPOSE,OBJECT_CLASS,DATE_CREATED,CREATED_BY,
	PRINT_COUNT,DATA_CHANGED,RESULTS_CHANGED,REPORT_FILE_NAME,SUPERSEDED,
	ALLOW_EDIT,ALLOW_PRINT,REPORT_STATUS,AUDIT
From [LabWare_Prod].dbo.REPORTS as r
inner join  #TempReportObj as t on r.REPORT_NUMBER = t.REPORT_NUMBER

-- fill out the REPORT_OBJECTS last and delete REPORT_OBJECTS first if want to delete report

Insert into dbo.REPORT_OBJECTS
(
	REPORT_NUMBER,[OBJECT_ID],[OBJECT_NAME]
)
select distinct
	r.REPORT_NUMBER,[OBJECT_ID],[OBJECT_NAME]
From [LabWare_Prod].dbo.REPORT_OBJECTS r
inner join [dbo].[SAMPLE] s
	on r.[OBJECT_ID] = s.SAMPLE_NUMBER